name: Tests
on:
  pull_request_target:
  push:
    branches:
      - master

permissions:
  contents: read
  actions: read

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: 8398a7/action-slack@v3.16.2
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
          
          
